### ISSUE TITLE
[v6.1.0] Management page no longer loads in Waterfox browser

### ISSUE THREAD

**Issue by luckysgb** [rthaut/deviantART-Filter#141]
The Filter Management page will not load in Waterfox after updating to 6.1.0 (despite the Firefox addon being marked as compatible at the corresponding version) and only shows a blank page. The following error appears in the developer console:

```
TypeError: Object.fromEntries is not a function (manage.js:77:94675)
```

It was working in 6.0.0 and older versions. I am using the latest version of Waterfox Classic (2020.05 64-bit)

**Comment by rthaut** [comment]
Thanks for the detailed report.

MDN claims `Object.fromEntries` is [compatible with Firefox 63+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries#Browser_compatibility), which was released on [October 23, 2018](https://www.mozilla.org/en-US/firefox/63.0/releasenotes/).

It seems odd to me that Waterfox doesn't support it, but I can easily swap that out for something else, likely either [Lodash's `fromPairs` method](https://lodash.com/docs/4.17.15#fromPairs) or [this ES6 alternative](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_frompairs).

@luckysgb are you able to load an unsigned add-on from a ZIP file, instead of from the Firefox Add-Ons site? If so, would you like me to send an unsigned version of 6.1.1 for you to test before I publish?

**Comment by rthaut** [comment]
This should be fixed in [v6.1.1](https://github.com/rthaut/deviantART-Filter/releases/tag/v6.1.1), which was just released.

If it still doesn't work after updating, feel free to add another comment to this issue (preferred if the error from the console is the same), or open a new issue (preferred if the console error is different now).

**Comment by luckysgb** [comment]
Sorry, I didn't have a chance to test this until now. I can confirm that this issue is fixed for Waterfox in v6.1.1. Thank you!

However, starting with v6.1.1, the addon shows as incompatible: "This add-on requires a newer version of Firefox (at least version 62.0). You are using Firefox 57.0." I don't think that was the case before. Was that intentional?

(FYI - Waterfox Classic is locked at 57.0 maintain support for pre-WebExtension addons, but stays up-to-date with other Firefox updates, such as security fixes.)

I'd fully understand if you make changes at some point that require a newer version, but as far as I can tell, it still works other than the version check.

**Comment by rthaut** [comment]
> However, starting with v6.1.1, the addon shows as incompatible: "This add-on requires a newer version of Firefox (at least version 62.0). You are using Firefox 57.0." I don't think that was the case before. Was that intentional?

@luckysgb It was indeed intentional, and was missed with the v6.1.0 release. I have made a new [issue for tracking the minimum required Firefox version](https://github.com/rthaut/deviantART-Filter/issues/143) which covers the details, but basically Firefox version 62+ is needed for a feature introduced in DeviantArt Filter v6.1.0. Waterfox evidently has included the change that was introduced in Firefox version 62. If there is a way to specify a minimum Waterfox version (separate from the minimum Firefox version), that would be a good compromise; feel free to continue the discussion in that new issue.
